# !GetAttはテンプレート内でのARN等の参照に使う。
# !Refはテンプレート内でのResourcesの参照に使う。
# DependsOnには!Refを使わない。
# CloudFomationはリソースの依存関係は!Refがついている場合には自動で解決される。
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  get ocn daily point automatically.
Globals:
  Function:
    Timeout: 3


# 開発環境か本番環境かを切り替えるためのパラメータ
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - development
    Default: development


# 環境変数の設定
Mappings:
  EnvironmentMap:
    development:
      S3BucketForCookie: cookie-for-iceman2


Resources:
  # Lambda用のIAMロール
  S3ReadonlyAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: for-lambda-s3-readonly-access-role
      # IAMロールがどのサービスまたはアカウントに対して信頼されるかを定義
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  # Lambda Layers
  PythonLibLayers:
    Type: AWS::Serverless::LayerVersion
    #DeletionPolicy: Retain # スタック削除時に削除しない
    Properties:
      LayerName: python-lib-layers
      Description: python3 library's for lambda
      ContentUri: create_python_lib_layers/python/
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7

  SeleniumDriverLayers:
    Type: AWS::Serverless::LayerVersion
    #DeletionPolicy: Retain # スタック削除時に削除しない
    Properties:
      LayerName: selenium-driver-layers
      Description: python3 library's for lambda
      ContentUri: create_selenium_driver_layers/headless/
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7

  # Lambda
  PushOCNDailyPoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/push_ocn_daily_button/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 60
      Environment:
        Variables:
          BUCKET_NAME:
            #!FindInMap [EnvironmentMap, !Ref Environment, S3BucketForCookie]
            !Ref S3Bucket
      #Role: !GetAtt S3ReadonlyAccessRole.Arn
      Layers:
        - !Ref PythonLibLayers
          # - !Ref SeleniumDriverLayers
  
    
  # S3
  S3Bucket: # 環境変数で定義したバケット名とかぶらない名前でtemplate内で宣言
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [EnvironmentMap, !Ref Environment, S3BucketForCookie]
      AccessControl: Private

  # EventBridge
  EventLaunch:
    Type: AWS::Events::Rule
    Properties:
      Description: AWS Lambda PushOCNDailyPoint
      EventBusName: default
      ScheduleExpression: cron(0 1 * * ? *) # 00:00(UTC)を基準として1時間ごとに実行
      State: ENABLED
      Targets:
      - Id: id_push_OCNDailyPoint # テンプレート内でユニークなリソースを識別する値。
        Arn: !GetAtt PushOCNDailyPoint.Arn
        RetryPolicy:
          MaximumRetryAttempts: 3
          MaximumEventAgeInSeconds: 300
